# Spring Application Name
spring.application.name=mtgleague

# PostgreSQL Database Connection Settings
spring.datasource.url=URL
spring.datasource.username=USERNAME
spring.datasource.password=PASSWORD
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Settings
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# HikariCP Settings (Optimized for AWS Lambda)
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=3000
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.max-lifetime=60000

server.port=5000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=MAIL
spring.mail.password=PASSWORD
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true